DELIMITER //
CREATE PROCEDURE GET_EMPLOYEES_BY_TITLE(IN title VARCHAR(50))
BEGIN
  SELECT * FROM employees WHERE `jobTitle` = title;
END;
DELIMITER;

CALL GET_EMPLOYEES_BY_TITLE('Sales Rep');

DELIMITER //
CREATE PROCEDURE GET_EMPLOYEE_TITLE_BY_ID(
      IN EMP_ID INT, 
      OUT JOB_TITLE VARCHAR(50)
    )
BEGIN
  SELECT `jobTitle` INTO JOB_TITLE FROM employees WHERE `employeeNumber` = EMP_ID;
END;

DELIMITER;

-- DECLARE THE VARIABLE TO HOLD THE VALUE OF THE OUT PARAM
SET @job_title = '';
CALL GET_EMPLOYEE_TITLE_BY_ID(1143, @job_title);
SELECT @job_title as 'Job Title';
